### ISSUE TITLE
Formium UI crash & error submitting error

### ISSUE THREAD

**Issue by darrenbarklie** [formium/formium#33]
### Current behavior

Attempting to delete a Form entity through the Formium dashboard UI.  From primary dashboard, clicking Edit Form Settings produces the "Something went wrong and we cannot load the page. Please try again." messaging.

After the crash, encounter a second error in attempting to submit bug report via popup from Report Feedback / Sentry popup.

### Expected behavior

To be able to access Settings of second form entity, to process deletion action.

### Reproducible example

Error is infinitely reproducible on single entity -- hard refresh back to dashboard.formium.io and reselect entities Settings recreates error.  However, other form entities function as expected.

### Your environment

Formium dashboard, not local to dev.

**Comment by jaredpalmer** [comment]
Thanks investigating right now.

**Comment by jaredpalmer** [comment]
What's the name of your project?

**Comment by darrenbarklie** [comment]
matchfitpass

**Comment by jaredpalmer** [comment]
This should be resolved. You'll be able to delete the form now. May I ask how or if you tried to submit the form (either on forms.formium.io or using the API)? Anyways, there was an empty array of `keys` in the database and the UI exploded. Unclear how you did that.

**Comment by darrenbarklie** [comment]
Thanks @jaredpalmer, I can confirm access to the internal dashboards again.

I had been trying to integrate via the API. I think my mistake client side was in attempting to call the API from a `/components/ctas` directory, rather than the `/pages` directory - which I've since learned subverts the usage of Next's `getStaticsProps()`. It's likely each empty key corresponds to a failed call on my side.

Thanks for the speedy resolution.  I really appreciate the quality dashboards and documentation.

**Comment by jaredpalmer** [comment]
Did you send an empty submission by any chance?

**Comment by darrenbarklie** [comment]
I was following this portion of documentation: https://formium.io/docs/react/frameworks/next-js#fetch-your-forms-schema and continuously returning `undefined`.
