### ISSUE TITLE
Clearing error state on page refresh

### ISSUE THREAD

**Issue by carolinerusso** [formium/formium#34]
Is there a way to clear form field errors when the page is refreshed?

Right now, state is maintained regardless of refresh and doesn't clear until the fields marked for validation meet the requirements.

**Comment by jaredpalmer** [comment]
On forms.formium.io or in the @formium/react package?

**Comment by carolinerusso** [comment]
@formium/react, using `useStaticQuery` and

`````
<FormiumForm
  components={{
    ...defaultComponents,
    FormControl,
  }}
  data={form}
  onSubmit={async values => {
    await formium.submitForm(form.slug, values)
    setSuccess(true)
  }}
/>
`````

**Comment by jaredpalmer** [comment]
Update to latest @formium/react and this should be fixed
