### ISSUE TITLE
Cannot found query fields with gatsby-source-formium 

### ISSUE THREAD

**Issue by x86chi** [formium/formium#35]
### Current Behavior

<img width="1267" alt="Screen Shot 2020-11-25 at 8 49 35 PM" src="https://user-images.githubusercontent.com/5278201/100224607-630b8f80-2f60-11eb-93b1-83ed66c51cfc.png">

> [Query with GraphQL - Web Integrations: Gatsby](https://formium.io/docs/react/frameworks/gatsby#query-with-graphql)

There is no fields in the above document. **another** four query fields was seen.

### Reproducible example

1. Use [Formium Gatsby Blog Starter](https://github.com/formium/formium/tree/master/examples/gatsby-starter-blog).
2. Get credentials from overview page.
3. Try `allFormiumForm`, `formiumForm(id or slug)` query. will be seen same output.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formium          | latest |
| React            | 16.12
| npm/Yarn         | npm | 
| Operating System | MacOS

**Comment by jaredpalmer** [comment]
Did you generate an API key for yourself?

**Comment by x86chi** [comment]
> 2. Get credentials from overview page.

Yes I have API key.

<img width="891" alt="Screen Shot 2020-11-26 at 12 11 14 PM" src="https://user-images.githubusercontent.com/5278201/100303711-8a09a600-2fe0-11eb-8c0f-0e4c6bdaa4c5.png">


I also modified the `.env.sample` and renamed it to `.env`.

```diff
 - FORMIUM_ACCESS_TOKEN=XXXXXXXX
+ FORMIUM_ACCESS_TOKEN=paste_your_access_token_here_do_not_wrap_with_quotes
- FORMIUM_ACCESS_TOKEN=XXXXXXXX
+ GATSBY_FORMIUM_PROJECTID=paste_your_project_id_here
```

**Comment by jaredpalmer** [comment]
Will investigate now

**Comment by carolinerusso** [comment]
@x86chi `name` is not in your schema, which is why you're getting the error. Neither is `slug`, `projectId`, `createAt`, or `updateAt` (also indicated by the red squiggly line in your graphql query).
