### ISSUE TITLE
Unable to Open Submissions UI

### ISSUE THREAD

**Issue by darrenbarklie** [formium/formium#45]
### Current Behavior

Hi Jared. I'm trying to open https://dashboard.formium.io/project/matchfitpass/form/demo/submissions however it generates following blocking error: 
![image](https://user-images.githubusercontent.com/3026261/103669865-c7af0680-4f70-11eb-846c-e76d6a43cd33.png)

### Expected behavior

Can review submission data.  A secondary form displays submission content correctly, just not the "newsletter" form.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formium          | 0.1.2 client, 0.1.1 react
| React            | next 10.0.3
| TypeScript       | n/a
| Browser          | Chrome 87.0
| npm/Yarn         |  6.14.8
| Operating System | macOS 11.1

**Comment by jaredpalmer** [comment]
Investigating right now

**Comment by jaredpalmer** [comment]
This should be fixed now

**Comment by darrenbarklie** [comment]
Thanks again!
