### ISSUE TITLE
Is Formium abandoned?

### ISSUE THREAD

**Issue by psicotecnico** [formium/formium#53]
Formium seems to be such a great idea and service and exactly what we where looking for. However it seems like the project has gone stale since the end of last year. No updates, many missing form inputs and a lot of open issues with no feedback.

Have this project been abandoned or is there some good things coming for this year? Would be great with an update.

**Comment by jaredpalmer** [comment]
Not even close! Still kicking! We're working on making Formium self-hostable. Unfortunately, that has meant not a whole lot of end-user updates this past month or so that's all

**Comment by psicotecnico** [comment]
Ok great! I have tried to get in touch with "sales" on the website in many different ways but did not receive an answer. Have you seen those emails?

**Comment by bureauberg** [comment]
Hello, 

Formium looks like a great idea indeed but I haven't seen any activity for ages. 
Basic form fields like a Date field and a Dropdown are still missing.

I assume this project has become stale indeed? 

Thanks
