### ISSUE TITLE
Builds that use caching / incremental sometimes fail 

### ISSUE THREAD

**Issue by richardfrankza** [formium/formium#65]
## 🐛 Bug report

Hi there. Current customer here super frustrated with broken builds. I first reported this with Netlify but it seems to be to do with the plugin as both Netlify and Gatsby cloud fail: 

See Netlify report: https://github.com/jlengstorf/netlify-plugin-gatsby-cache/issues/48

### Current Behavior

When a build runs on either Netlify or Gatsby cloud,  the build sometimes breaks and I get an error that the formium form cannot be retrieved. 

```
Unknown argument "slug" on field "Query.formiumForm".

GraphQL request:4:19
3 |     query SignUPQuery {
4 |       formiumForm(slug: { eq: "sign-up-form" }) {
  |                   ^
5 |         id
```

### Expected behavior

The build should find the form and pass.

### Reproducible example

Difficult to reproduce, it seems inconsistent and have something to do with caching

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formium          | 0.1.3
| React            | 16.14
| TypeScript       | N/A
| Browser          | N/A
| npm/Yarn         | N/A
| Operating System | N/A

**Comment by KyleAMathews** [comment]
Added PR to fix this issue https://github.com/formium/formium/pull/66
