### ISSUE TITLE
Email workflow cannot be tested, 403 disabled

### ISSUE THREAD

**Issue by darrenbarklie** [formium/formium#72]
### Current Behavior

Try to test email integration.  Blocking popup, with following message:
```
Unable to deliver email. 403 {"message":"Domain customer.formium-mail.com is not allowed to send:
Disabled for sending spam. Please contact support to resolve."}
```
![image](https://user-images.githubusercontent.com/3026261/143064148-0210ed9a-f06d-407f-847d-702788b204ca.png)

### Expected behavior

Successfully test email integration.

| Software         | Version(s) |
| ---------------- | ---------- |

| Browser          | Chrome 96 ARM64
| Operating System | macOS, M1

**Comment by edolyne** [comment]
@darrenbarklie I found that my forms were doing the same. If you utilize one of the custom mail server options, the workflow successfully completes.

**Comment by AronBe** [comment]
Hitting the same issue

**Comment by webforte** [comment]
Hello, are there any updates on this issue? The repo hasn't been updated in a while and simple forms (with default mail configuration) is still showing the same error. Thanks in advance!

**Comment by monsteronfire** [comment]
@webforte I know this doesn't directly resolve your problem, but a commenter above (@edolyne) suggested using custom mail server options. That suggestion worked for me.

This was the help article I used to get that working:
https://formium.io/guides/setup-gmail-smtp

Hope it helps :)

**Comment by madebydor** [comment]
I couldn't create an app password, looks like this feature is terminated.
How'd you guys implemented Gmail
<img width="1082" alt="Screen Shot 2022-08-21 at 21 34 36" src="https://user-images.githubusercontent.com/7532901/185807909-4cc58c12-024a-4d35-9fd0-89a39204226a.png">
?

**Comment by monsteronfire** [comment]
@madebydor, do you have 2-step verification set up on your Google account?

This is the guide I followed: https://support.google.com/mail/answer/185833
