### ISSUE TITLE
getFormBySlug - certificate has expired

### ISSUE THREAD

**Issue by camila-acosta** [formium/formium#76]
### Current Behavior

Hi there,

Hopefully we can get some support through here.

One of our clients is using Formium forms and including them on their website via getFormBySlug from @formium/client and FormiumForm from '@formium/react' and just today started to get a "certificate has expired" error when using getFormBySlug

![image](https://github.com/formium/formium/assets/67367750/8c49c1d7-ae8f-4e07-9b25-47524102bf58)

Unfortunately the support/sales team in Formium never replies to our questions even though our client is not in a free plan. Is there any workaround for this that you could advise please? 

Note: The forms are accessible via Formium and can be previewed without any issue using Formium websiste

Thanks for your help!

### Expected behavior

Being able to get a form by using the getFormBySlug

const form = await getFormBySlug(formSlug)

**Comment by samlogan** [comment]
We are also experiencing this, and it is affecting a live campaign for our client who is on a paid plan. Please help 🚨

**Comment by waynemcmahon** [comment]
Same issue here and no response from formium team yet

**Comment by mbuttler** [comment]
Same. The API site's SSL cert expired on the 30th. What's strange is that formium.io has a LE cert that's valid for *.formium.io, but the api.formium.io subdomain has an (expired) SSL certificate from Amazon.

**Comment by waynemcmahon** [comment]
@jaredpalmer Can you look into this please?

**Comment by wereHamster** [comment]
I just checked and the server has a fresh and valid certificate now. I hope they will write a post-mortem how this issue could happen in the first place and remain undetected for four days.

![image](https://github.com/formium/formium/assets/34538/b9d4778c-151b-476f-8d06-7f69d2cd6743)

**Comment by mbuttler** [comment]
Agreed, it's fixed. It would be nice if Formium got more attention than it does.

**Comment by camila-acosta** [comment]
Yes, it is still a bit unsettling that there is no official communication from Formium, but anyway it is great that it is solved now. I will close this now.
