### ISSUE TITLE
Current released @formium/react version is out of sync with documentation and examples

### ISSUE THREAD

**Issue by spetrunin** [formium/formium#9]
### Current Behavior

The documentation states that there is a FormControl component, that could be customized

https://formium.io/docs/react/components/form-control

Examples in this repo are also using FormControl, Textarea, and TextInput

But current version 0.0.20 which is released via NPM packages doesn't contain these changes, so the only way to run the latest is to specify the master branch version

### Expected behavior

Documentation, Examples should be in sync with the current released version

### Suggested solution(s)

release a new version? 👍 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formium          | 0.0.20 |

**Comment by jaredpalmer** [comment]
Yep. Will do.

**Comment by jaredpalmer** [comment]
Released
